{% set name = "perl-test-number-delta" %}
{% set version = "1.06" %}
{% set sha256 = "535430919e6fdf6ce55ff76e9892afccba3b7d4160db45f3ac43b0f92ffcd049" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Test-Number-Delta-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True # [not linux]
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl {{ perl }}
  run:
    - perl {{ perl }}

test:
  imports:
    - Test::Number::Delta

about:
  home: https://metacpan.org/pod/Test::Number::Delta
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Compare the difference between numbers against a given tolerance'

extra:
  recipe-maintainers:
    - Philippe Bordron