{% set name = "perl-math-random-mt" %}
{% set version = "1.17" %}
{% set sha256 = "069a1d98a619cba1f1ab91fbd6edceb642e84e7d162c4f0e2442139037b5b0da" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/F/FA/FANGLY/Math-Random-MT-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True # [not linux]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl {{ perl }}
    - libxcrypt
    - perl-test-number-delta
  run:
    - perl {{ perl }}
    - perl-test-number-delta

test:
  imports:
    - Math::Random::MT

about:
  home: https://metacpan.org/pod/Math::Random::MT
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'The Mersenne Twister PRNG'

extra:
  recipe-maintainers:
    - Philippe Bordron